version: '3.2'

services:
  mysql-server:
    container_name: mysqlserver
    hostname: mysql-server
    image: mysql:${MYSQL_TAG:-5.5}
    network_mode: ${NETWORK:-bridge}
    volumes:
       - mysql-datadir:/var/lib/mysql
       - ${PROVISIONING_PATH:-~/Code}:/provisioning
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-secret}
    ports:
      - ${MYSQL_PORT:-8989}:3306

  mysql57:
    container_name: mysqlserver57
    hostname: mysql-server57
    image: mysql:${MYSQL_TAG:-5.7}
    network_mode: ${NETWORK:-bridge}
    volumes:
    - mysql-datadir:/var/lib/mysql
    - ${PROVISIONING_PATH:-~/Code}:/provisioning
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-secret}
    ports:
    - ${MYSQL57_PORT:-8980}:3306

  mongo-server26:
    container_name: mongodbserver26
    hostname: mongo-server
    build:
      context: ./mongo/2.6/
    network_mode: ${NETWORK:-bridge}
    volumes:
       - mongo-datadir:/data/db
       - ${PROVISIONING_PATH:-~/Code}:/provisioning
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:27017
  
  elastic-server13:
    container_name: elastic-server13
    hostname: elastic-server13
    build:
      context: ./elastic/1.3/
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: ${NETWORK:-bridge}
    volumes:
       - elastic-datadir:/data/db
    restart: always
    ports:
      - ${ELASTIC_REST_PORT:-9200}:9200
      - ${ELASTIC_NODE_PORT:-9300}:9300
  
  elastichq:
    container_name: elastichq
    image: elastichq/elasticsearch-hq
    network_mode: ${NETWORK:-bridge}
    environment:
      - HQ_DEFAULT_URL=http://elastic-server13:9200
    ports:
      - ${ELASTICHQ_PORT:-5000}:5000
    links:
      - elastic-server13

  redis-server:
    container_name: redis-server
    image: redis
    hostname: redis-server
    command: ["redis-server", "--appendonly", "yes"]
    network_mode: ${NETWORK:-bridge}
    ports:
        - ${REDIS_PORT:-6379}:6379
    restart: always
    volumes:
      - redis-datadir:/data
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    network_mode: ${NETWORK:-bridge}
    environment:
      PMA_HOST: mysql-server
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
    ports:
      - ${PHPMYADMIN_PORT:-4003}:80
    links:
      - mysql-server
  
volumes:
  mysql-datadir:
  mongo-datadir:
  redis-datadir:
  elastic-datadir: